### ISSUE TITLE
npm installation error - postinstall

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [mrjmd/pdb#87] opened 2016-06-28 20:33 UTC
Right after I updated my source code, I removed "node_modules" and "typings" folder to execute a fresh installation, then I executed: "npm install" and it threw the following errors:
```
> pdb_ng2@1.0.1 postinstall /var/www/drupalvm/drupal/modules/contrib/pdb/modules/pdb_ng2
> typings install
└── (No dependencies)
npm ERR! Linux 4.2.0-38-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package @angular/common@2.0.0-rc.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.3 wants @angular/common@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.3 wants @angular/common@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/platform-server@0.0.0-PLACEHOLDER wants @angular/common@0.0.0-PLACEHOLDER
npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/drupalvm/drupal/modules/contrib/pdb/modules/pdb_ng2/npm-debug.log
```
[npm-debug.log.txt](https://github.com/mrjmd/pdb/files/337997/npm-debug.log.txt)

I found, it downloaded a lot of dependencies, but it looks like we should tweak "postinstall" instructions,

**Comment by sainsley123** [comment] 2016-08-12 18:28
I installed a fresh Drupal 8 install. Installed PDB and PDB_NG2 and ran "npm install." All of the dependancies installed properly without errors. I deleted the "node_modules" and "typings" folder and ran "npm install" again and it installed all the dependancies properly again. I was unable to reproduce this issue.

**Comment by acha5066** [comment] 2016-08-17 05:11
@sainsley123 What version of node were you running when you tried reproduce this error?

**Comment by sainsley123** [comment] 2016-08-17 10:23
@acha5066 My node version is 0.10.33.

**Comment by sainsley123** [comment] 2016-08-17 12:35
@acha5066 You make a good point. I upgraded to the latest (4.5.0) LTS version. I tested it again with the steps above and it re-installed without errors. Maybe there should be some definition of a "supported" or "works with" node version. I would recommend using whatever the current LTS version of node is.

**Comment by acha5066** [comment] 2016-08-25 07:09
Sorry a bit late in testing this. Couldn't get the latest version 8.x-1.0-alpha4 to work with either 0.10.33 or 4.5.0 or 6.0.0 versions of node. It gives me the same errors as the OP. The 8.x-1.0-alpha3 version installs fine however.

**Comment by acha5066** [comment] 2016-08-25 11:17
Update... downloaded the latest dev version. Installs fine. Has been fixed already.

**Comment by mrjmd** [comment] 2016-10-29 17:00
New version has been released, and some improvements beyond it have landed in the latest dev branch as well.

I'm closing this for now, if there are new install errors please open a new issue.

**Closed by mrjmd** 2016-10-29 17:00 UTC
