### ISSUE TITLE
ComponentDiscovery should not assume component.ts

### ISSUE THREAD

**Issue by phenaproxima** [mrjmd/pdb#43] opened 2016-04-29 17:53 UTC
What if a component is not written in TypeScript? The discovery service should probably assume something with the .js extension, then pdb_ng2 can add a hook_component_info_alter() implementation to adjust things.

**Comment by mrjmd** [comment] 2016-05-27 05:42
Marking this as a duplicate of [#63], which ties this to the existing development mode setting.

**Closed by mrjmd** 2016-05-27 05:42 UTC
Labels: duplicate
