### ISSUE TITLE
ng2 Showcase Example Component

### ISSUE THREAD

**Issue by derekreesemediacurrent** [mrjmd/pdb#39] opened 2016-04-29 15:40 UTC
We need a "flashy" Showcase component for Drupalcon.

My first thought is to build something demoing a reusable angular component and two way data binding at the same time.

I'm looking at building a panels IPE inspired set of fields with http://valor-software.com/ng2-dragula/index.html

**Comment by mrjmd** [comment] 2016-04-30 18:58
Marking as a duplicate of #20...

**Closed** 2016-04-30 18:58 UTC
Labels: duplicate, enhancement
